language: node_js
node_js:
  - "4"
addons:
  firefox: "49.0"
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - set -e
  - export PORT=8000
  - karma start --single-run --browsers Firefox
# TODO: - node_modules/.bin/eslint {js,test}/*
# Is this redundant?
# Travis checks package.json[scripts][test] for Node projects.
